### PR TITLE
include dot at the end of a CNAME record value

### LINKED ISSUE #2877: Include dot at the end of a CNAME record value
Some domain providers require a dot at the end of a CNAME record value. If the user then does not add it the domain itself would be added to the value.

Example for example.com:
| Type | Host/Domain | Value          |
| ------ | ------------------ | --------------- |
| CNAME |  s1._domainkey |  s1._domainkey.tutanota.com |

Would extend to the value **s1._domainkey.tutanota.com.example.com**

We just have to add the dot at the end in the add domain dialog.

| Type | Host/Domain | Value          |
| ------ | ------------------ | --------------- |
| CNAME |  s1._domainkey |  **s1._domainkey.tutanota.com.** |

### PR DESCRIPTION
**Pull request by vaf-hub**
fixes #2877

### CODE REVIEW

**Comment by jowlo** [comment]
Since we are doing the checks and generate these results (including the subdomains) on the server, we should also add the dot on the server side i think.

**Comment by jowlo** [comment]
Related to #2193 : How to display requested DNS records...

**Comment by vaf-hub** [comment]
> Since we are doing the checks and generate these results (including the subdomains) on the server, we should also add the dot on the server side i think.

If we add it on the server side then we will not need to change anything in the client, actually.

**Comment by jowlo** [comment]
Yip, that's what i meant

**Comment by vaf-hub** [comment]
closed because it will be fixed on the server side

**Pull request closed without merging**
