### PR TITLE
fix: paste inline images into composer

### PR DESCRIPTION
**Pull request by SethFalco**
## Inline Images

Currently, Tutanota doesn't do anything when pasting to the mail composer from the clipboard. Ideally, this should either:

* Insert an inline image
* Attach the image as an attachment

I do the former to be consistent with other email clients and because it's easier to achieve. It may be worth considering introducing an option, so users can select the preferred behavior.

This does the following:

* Update the Squire package and JavaScript file to the latest version so we can catch the `pasteImage` event, which was not available in the version used by Tutanota previously.
* When Squire catches an image paste, it triggers the `pasteImage` event which we implement a handler for.

This was tested on Debian 11 (Wayland) on Firefox Nightly 110. I've also tested the following scenarios which work as expected:
* Paste the image, close the mail editor modal and reopen the modal.
* Paste the image, save the draft, refresh the page, and continue my old draft and send the email.

Sorry for the use of `any`. Since `any` is used in other places, I figured for now I'll run with it and this could be addressed later.

I believe the `onPasteImage` handler was meant to receive a type `DataTransfer | null`, but in practice the object looked nothing like that. This one threw me off a bit. :thinking: 

As for `FileReader#onload` that one is just outdated types, this should be `FileReaderProgressEvent` but it's not available in the version of TypeScript used in the project.

Reference:
* https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/398
* https://github.com/microsoft/TypeScript/issues/4163

## Misc

* On the side I removed some unused imports and whitespace, and ran `npm run fix`.
* Visual Studio Code would report unstaged files from the Android directory that annoyed me due to it being a Java project. So I updated the `.gitignore` to also ignore the `.settings` directory. This line is also found in the standard templates from [github/gitignore](https://github.com/github/gitignore).

## Screenshots

image
> Pasting an image into the mail composer.

image
> Reading the email in a mailbox.org inbox using Thunderbird.

## Related

* Fixes https://github.com/tutao/tutanota/issues/5083
* Related to https://github.com/fastmail/Squire/issues/425

### CODE REVIEW

**Comment by charlag** [comment]
Thank you so much, I didn't have time to look at it properly yet but it would be great to fix the issue.

Notes for reviewers:
 - [ ] we do not want to include unrelated things to our .gitignore
 - [ ] please try to run update-libs on your own and see that the squire is indeed correct
 - [ ] please review all the squire changes in the actual file, especially from security standpoint
 - [ ] please check the changelog for squire

**Comment by SethFalco** [comment]
>  we do not want to include unrelated things to our .gitignore

Based on this, just updated the last commit so only ignore `.settings` in `app-android` specifically instead of adding the entire Java and Eclipse templates.

The rest I'll leave up to reviewers! Don't be afraid to hit me up if you want anything changed though.

**Comment by SethFalco** [comment]
PS: It looks to me that someone might be updating `package.json` manually rather than using `npm i`? Or perhaps using a tool to interface with `package.json` that does not preserve alphabetical order.

Just a heads-up, tools like `npm` and `yarn` insert dependencies in alphabetical order. It'd be nice if only this order would be committed to Git as otherwise when others install/update packages, it'll automatically sort it anyway and be prone to merge conflicts.

i.e. Just now I had to resolve a merge conflict due to dependencies since I'm using `npm`, and so the list is automatically sorted, but the commit to master didn't preserve alphabetical order.

**Comment by ganthern** [comment]
Update: I reviewed squire and managed to push my changes, so if you could rebase it we can include it in the release next week. 

Thank you again so much for tackling this, have a great weekend!

**Comment by SethFalco** [comment]
Ahh, awesome! Thanks for covering that for me! I was pretty busy so I was saving it for later.

Tomorrow I'll get this rebased. Hopefully, everything will be good for you to review next week. :+1:

**Comment by ganthern** [comment]
the github actions are stuck, I'll close and reopen to see if that helps

**Comment by ganthern** [comment]
merged with https://github.com/tutao/tutanota/pull/5304

**Pull request closed without merging**
