### PR TITLE
Ignore duplicate UID error when creating calendar events

### PR DESCRIPTION
**Pull request by johnbotris**
I suspect that the problem is something to do with getting rate limited when importing or accepting invites

### CODE REVIEW

**Review by charlag — APPROVED** [review]

**Review by charlag — APPROVED** [review]

**Comment by charlag** [comment]
@johnbotris can you rebase pls?

**Comment by johnbotris** [comment]
oh Arne and I decided to shelve this fix for the moment, as it needs some more done to it - It might be  that some events somehow have the same UID even if they arent the same event

**Comment by johnbotris** [comment]
do you know if i can convert this pull request or if i'd have to make a new one?

**Comment by charlag** [comment]
Screenshot from 2021-02-10 11-32-52
turns out I can do this too

**Comment by charlag** [comment]
We don't need it anymore

**Pull request closed without merging**
