### PR TITLE
Desktop Application

### PR DESCRIPTION
**Pull request by zeeshan595**
Added electron support so tutanota can be built as a desktop application.

### CODE REVIEW

**Comment by chatch** [comment]
Anyone built this and tested it already?

zeeshan could you publish a build to releases in your fork maybe?

**Comment by zeeshan595** [comment]
I actually thought I already did that but I think I forgot to publish the build. I uploaded a Windows, Mac and Linux build. I use Linux so I didn't test the other platforms but I am guessing they should work just fine.

https://github.com/zeeshan595/tutanota/releases

**Comment by zeeshan595** [comment]
I was getting a bit annoyed with having to build the application every time there is an update so now it gets the latest build from https://github.com/zeeshan595/tutanota/tree/tutanota-latest-electron-build and auto updates the electron application.

**Comment by Rob-Rychs** [comment]
Awesome work @zeeshan595! 
I was super lazy and just ran `nativefier app.tutanota.com` to make darwin electron desktop app for mac.

Works fine with peaking cpu-usage around 10%, hasn't memory leaked yet.
I'm curious to build and try your implementation and compare performances, let you know results.

**Comment by zeeshan595** [comment]
The most I could get the cpu usage up was ~6% with about 250MB ram. Also I didn't know about `nativefier` until like a month ago. But I would have probably done it with nativefire. My method's only "advantage" is that you have a local copy of the website but since you have to login and check for latest client build you might not even be able to see cached emails.

So the obvious choice is just to use nativefier. But I would try using nativefire with `mail.tutanota.com` instead of `app.tutanota.com` because i like the nice ui there.

**Comment by charlag** [comment]
Hi!
I am not really familiar with nativefier. I think it just puts a web page inside webview?
I think if we are to make an app it makes sense to serve JS locally and have at least some minimal system integration. So, I am for the Electron approach.
I am not sure that we have enough time to support desktop app at the moment, unfortunately. Because of that I think we cannot release it as an "official" app because we will be obliged to support it.
Nevertheless, thanks for your work, it may be useful for the future. In which state it is now?

**Comment by zeeshan595** [comment]
Hey, thanks for the feedback and yea i figured as much. I might upgrade this to use the newer `mail.tutanota.com`. Been busy with my own project to do much on this :D

I havn't had any issues using it so far, I didn't check extensions or upgrading to premium but it usually redericts users to the website when the app tries to open a new tab forexample clicking on `community`. But since it is locally stored i guess i can just remove the upgrade to premium page and redirect them to the website as well for that.

Should still be able to get the executable from here: https://github.com/zeeshan595/tutanota/releases

**Comment by ganthern** [comment]
I'm closing this because we now have a Desktop Client in Beta.

**Pull request closed without merging**
