### PR TITLE
Reduce number of requests when loading MailBodies for indexer

### LINKED ISSUE #2947: Optimize loading of entities after EventQueue processing
Load entities in chunks after EventQueue optimization. Especially for the search index MailBodies are processed one by one after log in.

### PR DESCRIPTION
**Pull request by johnbotris**
close #2947

### CODE REVIEW

**Comment by charlag** [comment]
We had some discussion and we missed the case where CREATE's might be delayed but MOVE's won't be. This shouldn't be common for loading after login (because move will be optimized away) but it is likely for websocket updates (which will come one by one).
We need to either flush deferred updates when some updates is received that mentions deferred CREATEs or disable it completely for realtime updates.

**Comment by charlag** [comment]
We keep it for now, we should revisit it

**Comment by ganthern** [comment]
> We keep it for now, we should revisit it

does this mean to close and try again later, or merge and improve upon it later?

**Comment by charlag** [comment]
I will close it for now because the branch is still there but we probably need to redesign our approach there

**Pull request closed without merging**
