### PR TITLE
Apply inbox rules in the background, fix #165

### LINKED ISSUE #165: Inbox rules are not processed in the background
Currently the inbox rules are only processed when the inbox folder is selected. Inbox rules should be processed in the background even when another folder or view is selected. After login we only load a fixed amount of emails which are then processed by the inbox rule handler. This does not guarante that all new emails are sorted correctly. 

- process inbox rules in worker thread
- store the last processed mail and load all new emails from this mail after login
- when changing the inbox rules in the settings add an option to process the inbox rules again for a given amount of emails (e.g.first 100).

### PR DESCRIPTION
**Pull request by charlag**

### CODE REVIEW

**Comment by snaggen** [comment]
I assume this means that the background process will decrypt the mails to be able to sort them. Does that mean that the mail notification can be improved to contain more info like the folder, sender and subject line?

**Comment by charlag** [comment]
Not *that* kind of a background. Currently they're only peocessed when your inbox folder is opened. This changes it to sort them even when you're in another part of the app.
What you want may come but much later, currently push identifier doesn't give you much info.

**Comment by snaggen** [comment]
Ahh... still a great improvement. So, I'm really looking forward to get this on my phone.

**Comment by charlag** [comment]
It is actually merged with 1ea3186592b41dbd44339b42355dcca62e410ae6 but something went wrong with Github

**Pull request closed without merging**
