### PR TITLE
fix: bump autolinker to latest version

### PR DESCRIPTION
**Pull request by thisislawatts**
Read more on the changes below, however I don't think this affects the way you're using it.
[https://www.npmjs.com/package/autolinker/v/3.0.0#upgrading-from-v2x---v3x-breaking-changes]()

### CODE REVIEW

**Comment by charlag** [comment]
Hey
Thanks for poointing it out that there's a new version.
Unfortunately, updating is not so simple. We need to review new version of the library and copy it into libs directory. We'll do it once we deal with more urgent things.

What is interesting though is that your link breaks Android app :thinking:

**Comment by thisislawatts** [comment]
Thanks for the quick response @charlag. That is very interesting I had not noticed that the external libraries were being stored within this repo. Has this been done to a safeguard against malicious content being served by the NPM registry?

Apologies for the oversight within the Android app, very interesting to see it's broken in that environment.

**Comment by charlag** [comment]
It's done for several reasons, including security: it's easier to diff them when bump them.

No need to apologize, we just encountered an error we've never seen before and I'm quite grateful for that.

**Comment by thisislawatts** [comment]
Closing as stale

**Pull request closed without merging**
