### PR TITLE
Add GitHub releases as an option

### PR DESCRIPTION
**Pull request by ayaen**
It is nice to show that explicitly as an option. Please correct me if I am wrong about this,
but I did notice android APKs get published as an Asset along with the source code.

### CODE REVIEW

**Comment by johnbotris** [comment]
That bullet-point refers to getting auto updates, which you won't get if you use the APK from github. Another bullet-point instead would make sense: " - If you just want a prebuilt version of the app, you can get it from the most recent android release page: https://github.com/tutao/tutanota/releases"

**Comment by ayaen** [comment]
Ah damn, you're right. But anyways people who still wish to be notified of updates 
on GitHub releases can use https://github.com/tutao/tutanota/releases.atom . 
I suppose this information would be useful for people.
I will edit this pull request to make the necessary change correcting my mistake.

**Comment by ayaen** [comment]
So I have made what I felt were corrections.

**Review by johnbotris — APPROVED** [review]

**Comment by johnbotris** [comment]
thanks!

**Pull request merged**
