### PR TITLE
[iOS] Fixes base64 decoding during AES Decrypt

### PR DESCRIPTION
**Pull request by murilopereirame**
This commit reverts the changes made to the Swift aesDecrypt function during the notifications' improvement.

The base64 decoding was rolled back to use our helper function.

Co-authored-by: André Dias <and@tutao.de>

Fixes https://github.com/tutao/tutanota/issues/7165

### CODE REVIEW

**Comment by charlag** [comment]
woah, yeah… good find!

neither commit nor the PR mention that this is iOS or related to alarms and I think they should

**Comment by murilopereirame** [comment]
> woah, yeah… good find!
> 
> neither commit nor the PR mention that this is iOS or related to alarms and I think they should

Thanks for the reminder, completely forgot about mentioning iOS. I'll fix it tomorrow

**Comment by antonlydell** [comment]
I tested the calendar notifications on the Tuta app on iOS v235.240709.0 and it still does not work.

**Comment by charlag** [comment]
@antonlydell this is not merged let alone released?

**Review by wrdhub — APPROVED** [review]

**Comment by antonlydell** [comment]
@charlag : You are right. I guess I was tired and misread the PR.

**Comment by wrdhub** [comment]
This was merged into dev-calendar manually.

**Pull request closed without merging**
