### PR TITLE
fix signup page terms and conditions links to tick checkbox when clicked, fixes #2487 

### LINKED ISSUE #2487: Clicking link in checkbox helptext also checks checkbox
For example: On signup page, clicking the link to the Terms and Services will cause the agree checkbox to be checked. It should not do this

### PR DESCRIPTION
**Pull request by Pa7Hub**
the text was rendered within the checkbox, so clicking would be registered as a checkbox click; separate text and checkbox and use new checkbox component
closes #2487

### CODE REVIEW

**Comment by jowlo** [comment]
Should be adapted to `SignupForm.js`, see #2561

**Comment by charlag** [comment]
Someone should adapt it I think since Patrik is unlikely to do that now

**Review by charlag — CHANGES_REQUESTED** [review]
adapt

**Comment by Pa7Hub** [comment]
> Someone should adapt it I think since Patrik is unlikely to do that now

Yeah, I could do it but it will take a while. It'd be best if someone else fixes it. Thanks!

**Comment by johnbotris** [comment]
the fix is now part of #2561

**Pull request closed without merging**
