### PR TITLE
[desktop] clear dock badge on each window focus, close #1971

### LINKED ISSUE #1971: [mac] Unread mail indicator is not cleared when using the app
>I've to restart my Mac client every time I get an email, because the "you got new mail"-icon does not disappear after reading my mail. This makes the Mac client almost unuasable. Is this a known issue, and if so, are there any workarounds/fixes known, other than restarting the application?

I think @vitoreiji

### PR DESCRIPTION
**Pull request by ganthern**
this fix will clear the dock icon badge on mac when **any**
window is focused (including newly created), in addition to
the "activate" callback that's already on the app object
(see DesktopMain.js).

### CODE REVIEW

**Comment by charlag** [comment]
I believe this might be not enough. If you are inside the app, receive email and read it, will it disappear or stay?

**Comment by ganthern** [comment]
atm, we don't show a notification at all if the user the notification is sent to is currently logged in & focused. So no Badge to clear in that case. If the window is focused and not logged in, though, it's still not cleared.

**Comment by charlag** [comment]
Didn't know we don't send them.
I would say that it's rare that notification is received while you are on the login screen but maybe it's better to either do it like on Android:
https://github.com/tutao/tutanota/blob/a51ae4a0a6f08d9dac8d6ee70267e096a23205da/src/mail/MailView.js#L524-L529


or just clear after login too, what do you think?

**Comment by ganthern** [comment]
Now clearing whenever the URL changes. we're subscribing to that event anyway to check the URL we're navigating to.

**Pull request merged**
