### PR TITLE
target android api v33

### LINKED ISSUE #5627: Update target API level to 33
> As of August 31, 2023, new apps and app update submissions must target API level 33 (Wear OS must target API 30). Existing apps must target API level 31 or newer to remain available to new users on devices running Android OS higher than your app's target API level. To save time and effort, you can use the new [SDK Upgrade Assistant](https://notifications.google.com/g/p/ADa0GC8SvYXZsU4peakVWWkzrhbUWamnCLRgOPS-iYKXoxHkoQtCbuguRh7PoQ826UTL4QudHgdNopENJaaF2PHQdrrSK7FX21aoqVaUQKuYMTyeUE3gYlbDrTC9t2tgBdA97un6RN_K7JcLu4lAxoPUPbZfWdUYFFthMm7utcpOFEQIFS2xPbrPVy3HJBj2CCyjjGJ3T_V7ppnHZA) in Android studio. You will also be able to request an extension to November 1, 2023 if you need more time to update your app. [Learn more](https://notifications.google.com/g/p/ADa0GC-ZOgKarAcXYt0mBERHHoICgSFjammxghnqrAtcfBY-T4D4SY7AVljjMs3ajRxXu-kKc2kCcPD-9i7bp3OI8A4iE5dK2Lb2Py2ct6j_NeJu4HvYa1MTNpY8PhvIMDha9z9lNk9bTe74TVG6dGkU7qvbZ3yXIxWyOq155p1rhN8kyFzsqW4lB8JX0DjslkPumNYc5VJWWpmbmZMoXp2f0a_kaNWthYB8f72hzFmjWDhjqd4O-Xbr)

## Test Notes (android 13 and pre-13) 
* [ ] battery optimization permission is still requested
* [ ] mail notification works
* [ ] access permissions work for "normal" files and for media
* [ ] login works (with and without saving)
* [ ] offline works
* [ ] attachments work
* [ ] signup works
* [ ] account upgrade works

## Test Notes (android 13) 
* [ ] stopping the app from the android task manager does not lead to errors (it should show up there while running the foreground service?)
* [ ] notification permission is requested on login after install, together with the battery optimization one.
* [ ] denying or dismissing the activity on the notification permission request does not lead to errors

## Release Notes:
* [ ] updated translations for the battery optimization request dialog to mention notification permissions as well

### PR DESCRIPTION
**Pull request by ganthern**
fix #5627

### CODE REVIEW

**Comment by charlag** [comment]
Did you check whether we need to fix/update anything for the behavior differences?

**Comment by ganthern** [comment]
stuff seems to work fine :shrug:

**Comment by charlag** [comment]
wrong answer

should request another media permission?
https://developer.android.com/about/versions/13/behavior-changes-13


do we need to manually request notifications permission now?

**Comment by ganthern** [comment]
For some reason, I can't make the app show up in the task manager anymore... I wanted to try killing it from there and see if it breaks, but oh well.

**Review by wrdhub — APPROVED** [review]

**Pull request merged**
