### PR TITLE
Calendar import/export compatibility improvements

### PR DESCRIPTION
**Pull request by charlag**
- Handle import with nonsense end time
 - Add type to exported all-day times

### CODE REVIEW

**Comment by bedhub** [comment]
We have a problem now importing ical events from a different source and they seem to define it differently. In the file from schulferien.org the end date is on the next days and in the file from calendarlabs.com the end date is on the same day. Is there something in the RFC to distinguish end date definition?

schulferien.org
```
BEGIN:VEVENT
SUMMARY:Ostermontag
DTSTART;VALUE=DATE:20200413
DTEND;VALUE=DATE:20200414
END:VEVENT
```

calendarlabs.com
```
BEGIN:VEVENT
SUMMARY:Easter Monday
DTSTART:20190422
DTEND:20190422
END:VEVENT
```


[german_holidays_different_sources.zip](https://github.com/tutao/tutanota/files/4358328/german_holidays_different_sources.zip)

**Comment by charlag** [comment]
https://tools.ietf.org/html/rfc5545#section-3.8.2.2

>   Description:  Within the "VEVENT" calendar component, this property
      defines the date and time by which the event ends.  The value type
      of this property MUST be the same as the "DTSTART" property, and
      its value MUST be later in time than the value of the "DTSTART"
      property.  Furthermore, this property MUST be specified as a date
      with local time if and only if the "DTSTART" property is also
      specified as a date with local time.

Google Calendar exports all-day events like
``` 
DTSTART;VALUE=DATE:20200321
DTEND;VALUE=DATE:20200322
```
for all-day event on 21d. So it seems like VALUE=DATE means "excluded" but I can't find anything in RFC which would say that.

>    The following is an example of the "VEVENT" calendar component
      used to represent a multi-day event scheduled from June 28th, 2007
      to July 8th, 2007 inclusively.  Note that the "DTEND" property is
      set to July 9th, 2007, since the "DTEND" property specifies the
      non-inclusive end of the event.

       BEGIN:VEVENT
       UID:20070423T123432Z-541111@example.com
       DTSTAMP:20070423T123432Z
       DTSTART;VALUE=DATE:20070628
       DTEND;VALUE=DATE:20070709
       SUMMARY:Festival International de Jazz de Montreal
       TRANSP:TRANSPARENT
       END:VEVENT

>    The "DTSTART" property for a "VEVENT" specifies the inclusive
      start of the event.  For recurring events, it also specifies the
      very first instance in the recurrence set.  The "DTEND" property
      for a "VEVENT" calendar component specifies the non-inclusive end
      of the event.  For cases where a "VEVENT" calendar component
      specifies a "DTSTART" property with a DATE value type but no
      "DTEND" nor "DURATION" property, the event's duration is taken to
      be one day.  For cases where a "VEVENT" calendar component
      specifies a "DTSTART" property with a DATE-TIME value type but no
      "DTEND" property, the event ends on the same calendar date and
      time of day specified by the "DTSTART" property.

so DTEND *should* be exclusive in all cases?

In fact, the whole RFC doesn't have an example for DTEND with just a date, it's either date-time or VALUE=DATE

**Comment by charlag** [comment]
I've found one helpful quote:
> Authors typically publish the end date of a multi-day event as the last day the event occurs. This is called an inclusive end date.
Unfortunately the iCalendar standard requires publishing the day *after* the the last day of a multi-day event. This is called an exclusive end date. 

http://microformats.org/wiki/dtend-issue

so we have to guess as far as I understand

here's a 14 yo thread from the sunbird, discontinued calendaring app from Mozilla where someone talked to the spec author via email and spec author says "yeah it is inclusive actually" but then they tried out other apps and all of them encoded it as exclusive.

So I'm not sure what to do and if we can infer it but at least it doesn't seem like we are doing something really wrong.

**Comment by bedhub** [comment]
We should handle end date like defined in the RFC as exclusive date.

https://tools.ietf.org/html/rfc5545#section-3.8.2.2
> ... value MUST be later in time than the value of the "DTSTART"

https://tools.ietf.org/html/rfc5545#section-3.6.1
>  ... The "DTEND" property  for a "VEVENT" calendar component specifies the non-inclusive end
      of the event.  

I think the example file from calendarlabs.com does not comply to the RFC. Do be more relaxed we can handle this case (start and end are the same) like there is no DTEND at all.

https://tools.ietf.org/html/rfc5545#section-3.6.1
>  For cases where a "VEVENT" calendar component specifies a "DTSTART" property with a DATE value type but no "DTEND" nor "DURATION" property, the event's duration is taken to be one day.  

> For cases where a "VEVENT" calendar component specifies a "DTSTART" property with a DATE-TIME value type but no "DTEND" property, the event ends on the same calendar date and time of day specified by the "DTSTART" property.

Another issue with this file is that the default value type for DTSTART and DTEND is DATE-TIME but actually the value is of type DATE.

https://tools.ietf.org/html/rfc5545#section-3.8.2.2
> Value Type:  The default value type is DATE-TIME.

**Comment by charlag** [comment]
@bedhub please re-review

**Pull request merged**
