### PR TITLE
[android] improve slow attachment uploads by removing read timeout

### PR DESCRIPTION
**Pull request by ganthern**
due to TCP buffering we don't actually get to know when our data was
written to the network.
this may cause us to copy a file to the TCP buffer and immediately start
waiting on a server response.
on slow connections, this trips the 15s HTTP read timeout.

removing the timeout and relying on the OS to tell us if the connection
breaks should help with this.
for this, we convert all SocketExceptions into ConnectionErrors.
There's still sort of a timeout because the server will stop listening
after 10 (?) minutes to prevent slow loris.

also add a redraw on the minimized mail editor so we see a change in
status immediately

#4035

### CODE REVIEW

**Review by johnbotris — APPROVED** [review]
just need test notes and you can mark as done

**Comment by ganthern** [comment]
## Testing
simulate a slow connection on the android device (see the confluence wiki how-tos) and try to upload a large attachment (send mail and minimized mail editor draft)

* [ ] there is no timeout error after 15 seconds
* [ ] if the upload takes longer than 10 minutes, the upload fails with a connection error (you're offline)
* [ ] otherwise, it eventually finishes

### Mailing Regressions
* [ ] replying to email to internal recipient, reading email as recipient works    
* [ ] sending secure email to external recipient with attachment and pre-shared password works
* [ ] reading email as external recipient works
* [ ] downloading attachment works
* [ ] replying with attachment works
* [ ] reading email as internal recipient works
* [ ] sending unsecure email to external recipient with attachment works
* [ ] replying with attachment, read email as internal recipient works
* [ ] sending and receiving with alias email address works
* [ ] sending mail to non existing external recipient works (??)
* [ ] receiving bounce mail containing origin mail works
* [ ] external: store preshared password in browser works and doesn't prevent the notification link from working
* [ ] external: receiving a mail after changing the preshared password prevents auto login
* [ ] external: replying with attachment works 
* [ ] external: receiving mail with attachment works
* [ ] external: receiving a mail with password via SMS works (??)
* [ ] notification for new mail are sent
* [ ] mail export works

**Comment by charlag** [comment]
So the original idea was to see whether the data is written. I believe it works in other cases (e.g. see Tusky) but it might be the same problem.
Doesn't `setFixedLengthStreamingMode()` already disable internal TCP buffer?
IMO waiting for 10 minutes to realize that nothing was actually uploading for the last N minutes is just unacceptable experience.

**Comment by ganthern** [comment]
> So the original idea was to see whether the data is written. I believe it works in other cases (e.g. see Tusky) but it might be the same problem. Doesn't `setFixedLengthStreamingMode()` already disable internal TCP buffer? IMO waiting for 10 minutes to realize that nothing was actually uploading for the last N minutes is just unacceptable experience.

`setFixedLengthStreamingMode()` disables the buffer internal to the UrlConnection Java Object, but the OS still maintains another buffer in the TCP stack which we can't get rid of because there's no API to configure it. Maybe that would be possible with raw sockets.

The Buffer seems to have at least a few hundred KB capacity. Currently, with a 256k file, the upload will be buffered completely  on the first flush and then run into the read timeout after 15s, while with a larger file, there will be several flushes to the OS buffer before blocking for a while. In this case, a failure will occur if the last chunk takes longer than 15s to upload.

Since there are no callbacks or status events during the upload, implementing a shorter timeout than the 10 minutes enforced by the server would require to use an async upload with a watchdog and/or spreading the upload over several requests.

If there's truly no connection, the JVM will throw a SocketException sooner than 10 minutes.

**Comment by charlag** [comment]
I see.

I think we still need to have upload tracking, even if it has much more liberal timeout (like a minute). Like I said before, instead of calling `IOUtils.copy()` we should `write()` in a loop and see that there's some progress. This doesn't require async upload by itself but probably requires a timer that we can reset.
 
We do the same in the web version (effectively) and I think we might be running into the same issue on the web but we still do this.

I believe you on `SocketException` but I also don't want to rely on that - since we set no timeouts it theoretically shouldn't even happen.

So my question is, did you try implementing a loop for writing? I think it's still worth exploring by either you or someone else.

**Comment by charlag** [comment]
After discussion with @ganthern we found out that we both would like to do watchdog/timeout kind of thing but this should probably be done separately and possibly with Kotlin/Coroutines. So we will make sure there are separate issues for the reported problem (can't upload files on slow network) and the problem we know about (don't interrupt the process early enough).

**Review by charlag — APPROVED** [review]

**Pull request merged**
