### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by Dutisto**
Hi, 

As I proposed here : https://github.com/tutao/tutanota/issues/417 , this is the docker support for Tutanota. Basically you got two folders, one for the Android app and one for the web client. The web client is simple, it install the repo and launch the app. I tried setting up a reverse proxy using nginx but the app couldn't reach the server. 

For the android app,  you run the container and you got the apk signed ready to be installed in output. You can change your key password if you want in the `docker-entrypoint`.

I also updated the README.md with commands to run.

Hope you like it =]

### CODE REVIEW

**Comment by charlag** [comment]
Hi! I think this is awesome. We need to be able to build Android app from the command line anyway so this may be a great help! At the moment we are a little bit busy with beta bug fixing but we're certainly getting back to it a little bit later. Do you think we can pass keystore and required flavor to the Android app container somehow?
Thanks a lot!

**Comment by Dutisto** [comment]
Glad you like it !
For the keystore, i think this is possible and i'll look into it. But I don't understand what you mean by the Android flavor. Could you explain a little more ?

**Comment by charlag** [comment]
Yeah, sorry, my mistake, they're not flavors but build variants. We have one for the debugging using remote webpage, debug for copied webpage and one for the release. See app-android/app/build.gradle.

Keystore is .jks. Yeah, we want to import it into container.

**Comment by Dutisto** [comment]
OK now I understand. I can definitely look into that =]

**Comment by charlag** [comment]
Would be amazing, thanks!

**Comment by Dutisto** [comment]
Hi, 
I worked on what you asked me. I think I got something that may satisfy you. I updated the `docker-entrypoint.sh` so now, you can : build debug/debugDist simply by running `docker run --rm -v $(pwd):/outputs tutanota:android -b debug|debugDist`, and you can also use your key for signing `docker run --rm -it -v myKeyFolder:/keystore -v $(pwd):/outputs tutanota:android -b release -k myKey.jks -a myKeyAlias`.

Users can still simply build release build with the built in keystore, by just running `docker run --rm -v $(pwd):/outputs tutanota:android -b release`.

Everything is update to date in the README.md.

Tell me what you think about this =]

**Comment by charlag** [comment]
This sounds awesome, thank you, I'll test it when I'll have time!
There's one more thing: we should use `node dist prod` instead of `node build prod`. Sorry for misleading you, we made much bigger build because we made this mistake the first time we published the app. You can change it or I'll change it later when I will be merging it.

**Comment by Dutisto** [comment]
Don't bother, I already changed it. I also updated the error handling, because it was really ugly^^.
Would you mind point me the change between `node dist prod` and `node build prod` ?

**Comment by charlag** [comment]
Thanks a lot!
`build` script does not bundle things. `dist` script creates optimized production build. You can check them out yourself.

**Comment by charlag** [comment]
I just wanted to squash and rebase things on this branch but Github just closed this PR
:thinking: 
Sorry!
I hope you don't mind if we use this at least for Android builds for now, if you will want to maintain authorship, please reopen with Docker changes.

**Pull request closed without merging**
