### PR TITLE
Add alternative date to the calendar view

### PR DESCRIPTION
**Pull request by HassanHeydariNasab**
Hi,
I added alternative/secondary representation of the date to month calendar and week calendar using Intl API. for example when I change the language to Persian, I can see Jalali date alongside Gregorian one.
It is disabled by default. you can enable it at Appearance settings.
Thanks

### CODE REVIEW

**Comment by charlag** [comment]
Hi!
Thanks for the PR.
I wanted to ask whether it's possible to base it on the language? We already did something similar for Commonwealth/American English and date format and if we could get away without more options it would be great.

**Comment by HassanHeydariNasab** [comment]
> Hi!
> Thanks for the PR.
> I wanted to ask whether it's possible to base it on the language? We already did something similar for Commonwealth/American English and date format and if we could get away without more options it would be great.

Yes, it's based on the language.

**Comment by charlag** [comment]
I meant, can we just have two language options instead of a separate picker?

**Comment by HassanHeydariNasab** [comment]
> I meant, can we just have two language options instead of a separate picker?

What do you mean by a "separate picker"?

**Pull request closed without merging**
