### PR TITLE
Remove alternating background colors on email list

### PR DESCRIPTION
**Pull request by ajgraves**
As mentioned on this [reddit thread](https://www.reddit.com/r/tutanota/comments/gkiyq9/unread_emails/), I'm submitting this PR that removes the alternating background from the list of emails. I'll admit this is far from perfect and can be further improved on, but here we have it.

- Adds a bottom and top border to each list item of 1px, and is colored based on selected/not selected.
- Removed now unused styles and everywhere that added odd-line styling

### CODE REVIEW

**Comment by charlag** [comment]
Hi
Thanks for the PR
I proposed something similar in the autumn last year but we decided to not change it back then.
I'm not sure if we want to change list design in the near future, I would first improve fields/buttons/dropdowns.
Maybe you could include some screenshots so that we don't have to build it to discuss it, thanks!

**Comment by ajgraves** [comment]
Certainly, I have a few posted at [this imgur album](https://imgur.com/a/m1Q5L1t/). They don't show very much though, I'll try to grab screenshots with more to show in the list.

**Comment by ajgraves** [comment]
I added a few more to [another imgur album](https://imgur.com/a/1RlqJVg)

**Comment by charlag** [comment]
Hi
We had some discussion about it again and we are not ready to give up on it. Maybe we will revisit it when we change design some more.
About your implementation: I think borders were colliding and selection looked kinda strange so it would need more work in any case.
Thanks for the proposal!

**Pull request closed without merging**
