### PR TITLE
[linux] Update the .desktop entry to reflect recent Tutanota name change

### PR DESCRIPTION
**Pull request by iakmds**
**Background:**

Currently, the desktop entry for linux shows a) **Tutanota Desktop** as the application title and b) **The desktop client for Tutanota, the secure e-mail service.** as the description.

**Changes:**

This PR changes all strings from "Tutanota" to "Tuta" inside the [DesktopIntegratorLinux.ts](https://github.com/tutao/tutanota/commit/8a3aa3e09f2a59436e54ef33d83c1fc2143f3b31) to reflect the recent name change from Tutanota to Tuta. Perhaps it should be "Tuta Mail" instead of just "Tuta"? Let me know what you think.

### CODE REVIEW

**Comment by charlag** [comment]
hi, thanks for the change!

Yes, it should say Tuta Mail, I'm surprised it's not pulled out of some other metadata to be honest.

I don't think we should change that `X-Tutanota` header though

**Review by charlag — APPROVED** [review]
Ah thank you so much!
I think we could also drop "Desktop" part now that I look at it.

**Comment by iakmds** [comment]
Should be good now :)

**Comment by charlag** [comment]
Ah thank you!

**Comment by charlag** [comment]
Sorry we were tweaking CI to be able to build the PRs from forks!

**Pull request merged**
