### PR TITLE
Added needed files for Tutanota Firefox OS app

### PR DESCRIPTION
**Pull request by elninosi**
This is in reference to: https://tutanota.uservoice.com/forums/237921-general/suggestions/9656664-create-firefox-os-app

This pull request includes everything you need to publish hosted app for Firefox OS.

I would suggest you to submit app to Firefox Marketplace. 
Steps: 
1) On the server side you need to serve manifest the right way. More info: https://developer.mozilla.org/en-US/Apps/Build/Manifest#Serving_manifests

2) Submit app to Firefox Marketplace (https://marketplace.firefox.com/developers/submit/) More info about the process: https://developer.mozilla.org/en-US/Marketplace/Publishing/Introduction

I can help you with publishing, as I'm an App reviewer on Firefox Marketplace. I would love to see Tutanota available on Firefox OS devices.

### CODE REVIEW

**Comment by Schoewilliam** [comment]
Hoho. Neat PR

**Comment by elninosi** [comment]
Ping?

**Comment by mpfau** [comment]
Thanks, this is great! We already implemented the change on the server side (mime type) and organized a test device. Will test your changes and merge afterwards.

**Comment by elninosi** [comment]
Great, thanks for this info!

**Comment by elninosi** [comment]
Great! Do you need help to get app to Firefox Marketplace? Have you submitted yet?

**Comment by mpfau** [comment]
We have to wait for the next Tutanota release. Should only take a couple of days... :)

**Comment by elninosi** [comment]
Is this now merged into production?

**Comment by mpfau** [comment]
Yes, but I forgot to update the build script to include the manifest. That is why https://app.tutanota.de/manifest.webapp returns 404.

This has been fixed with commit 53b67dc which will be included in the next release.

**Comment by elninosi** [comment]
I can see that https://app.tutanota.de/manifest.webapp is now accessibly

Can you please submit app: https://marketplace.firefox.com/developers/submit/
Thanks!

**Comment by mpfau** [comment]
@elninosi Wow, you are fast. Has just been released... :)

I have added it to the marketplace but it will take up to five days till the app has been validated.

There are a few things we should follow up on if time permits:
* Add a reference to the appcache configuration
* Decide on which Firefox APIs should be used from the app for better integration (e.g. fullscreen, notifications etc.)
* Update the Screenshots

**Comment by elninosi** [comment]
@mpfau I've just approved the app. No need to wait :)

I agree with you. We can definitely improve this app on Firefox OS in the future with some of suggested improvements.

**Comment by elninosi** [comment]
Here are screenshots from Firefox OS device. Please update them on Firefox Marketplace.

**Comment by mpfau** [comment]
Great, thanks! Just updated the screenshots... :)

**Pull request merged**
