### PR TITLE
Fix the `DropDown`'s navigation and it's filter including cosmetic periods

### LINKED ISSUE #5353: Dropdown filter issues
* When a dropdown with filter is opened in the desktop layout (move mail with more than 10 folders), it's not possible to navigate down to the filtered list with the arrow keys, only with tab
* The same dropdown on mobile (at least android) does not open the keyboard, you have to tap the input before being able to type.
* for folders, it's also searching/matching the dots we use to show the nesting.

## Related:
https://github.com/tutao/tutanota/issues/4007

## Test notes
Try the move folder button for the mail for an example of a dropdown. There must but around 10 folders on the account to work.
- [ ] On Desktop/Web App
  - [ ] Pressing the down arrow after opening the dropdown causes the first item to be focused
  - [ ] Pressing the up arrow after opening the dropdown causes the last item to be focused
  - [ ] Pressing the up and down arrows after already having focused an item moves the focus to the previous and next item respectively.
- [ ] On Android and iOS:
  - [ ] The filter input is focused when opening the dropdown.
- [ ] On any:
  - [ ] Searching for a subfolder by name works
  - [ ] Searching for '.' with subfolders on the account returns nothing
  - [ ] Searching for '.' with subfolders on the account that include '.' in their names returns the subfolders

### PR DESCRIPTION
**Pull request by rezbyte**
Closes #5353.

### CODE REVIEW

**Review by charlag — COMMENTED** [review]
It seems to work great but I have some questions about the behavior:

 - on desktop it was focusing the filter just fine for me before and still does
 - on mobile it still doesn't focus the filter and I don't think it should?
 - screen readers don't read the indentation of folders but they haven't been doing it before either, we probably need a custom translation like "folderName, {level} levels deep". Doesn't have to be in this PR ofc. Just wanted to point out that what we are doing now with `label`/`text` doesn't seem to have an effect, at least on TalkBack
 - how TalkBack reads items is kind of weird now. Before for a folder named "2" it would read "two menu item", now it reads "two menu item two". I am not sure what's causing this, aria role perhaps?

**Comment by rezbyte** [comment]
>     * on desktop it was focusing the filter just fine for me before and still does

It was not focusing the filter automatically on Chromium.

>     * on mobile it still doesn't focus the filter and I don't think it should?

It should focus the filter as that is what the issue states. Personally, I agree with the issue as I have a lot of folders myself so I always search when it opens.
 
>     * screen readers don't read the indentation of folders but they haven't been doing it before either, we probably need a custom translation like "folderName, {level} levels deep". Doesn't have to be in this PR ofc. Just wanted to point out that what we are doing now with `label`/`text` doesn't seem to have an effect, at least on TalkBack

That is a good idea, I will address this here.

>     * how TalkBack reads items is kind of weird now. Before for a folder named "2" it would read "two menu item", now it reads "two menu item two". I am not sure what's causing this, aria role perhaps?

Interesting, I will have to investigate it.

**Comment by charlag** [comment]
Hey, thanks for clarification. I think I still disagree about the keyboard and filter on mobile. I think it's very unconventional to have a filter that's pre-focused in such case: it is not a search filter per se and that's probably pretty confusing if you have a keyboard open by default. Most people don't enjoy typing on mobile keyboard so much so I would not optimize for this use case.

Other issues that are related but are out of scope:
 - dropdown shifts off-screen if keyboard is open which is a big
 - it shouldn't even be a dropdown but rather should be a "bottom sheet" with actions or similar

I feel pretty confident we shouldn't focus but if you feel strongly about it I would be glad to talk about it more and maybe also get more opinions.

**Comment by rezbyte** [comment]
>     * dropdown shifts off-screen if keyboard is open which is a big

I believe there is already an issue for this. #761

>     * it shouldn't even be a dropdown but rather should be a "bottom sheet" with actions or similar

It might be nicer to have more of the list visible than a bottom sheet allows. Other email clients seem to use a standard dialog.

> I feel pretty confident we shouldn't focus but if you feel strongly about it I would be glad to talk about it more and maybe also get more opinions.

I did a quick check and other apps do not focus automatically. We can leave it as-is.

**Review by wrdhub — APPROVED** [review]

**Pull request merged**
