### PR TITLE
Don't allow empty email addresses on signup/alias creation

### LINKED ISSUE #4226: Can attempt to create accounts, aliases, users, and groups with empty email address
3.69.9

1. Open signup wizard
2. Select subscription
3. Type in valid password twice
4. Tick all the boxes
5. Click "next"
6. See that signup process starts and fails with an error

# Test notes
## Sign up
- [ ] Go to sign up for an account (can be a free account).
- [ ] Only enter a password and agree to terms and age minimum checkboxes. Do not touch the email address field.
- [ ] Verify that it tells you to enter an email address rather than an unexpected error.

## Alias
- [ ] Go to create a custom alias in User Settings -> Email
- [ ] Do not enter or edit anything and just submit the form as-is.
- [ ] Verify that it tells you to enter an email address rather than an unexpected error.

## Users
- [ ] Go to create a user in in Admin Settings -> User management
- [ ] Only enter a password. Do not touch the email address field. User name can be anything or left empty as it is optional.
- [ ] Verify that it tells you to enter an email address rather than an unexpected error.

## Groups
- [ ] Go to create a user in in Admin Settings -> Groups
- [ ] Do not enter or edit anything and just submit the form as-is.
- [ ] Verify that it tells you to enter an email address rather than an unexpected error.

### LINKED ISSUE #4244: Uncaught BadRequestError when trying to add empty alias while setting up custom email domain
On test 3.96.11:

```
Feedback v3.96.11 - BadRequestError - PREMIUM - Browser
Client: Browser
Type: PREMIUM
Tutanota version: 3.96.11
Timestamp (UTC): Tue, 31 May 2022 09:25:26 GMT
User agent:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0
BadRequestError
Error message: 400: N3OQmt3----0 | POST /rest/sys/mailaddressaliasservice
Stacktrace:
BadRequestError. 400: N3OQmt3----0 | POST /rest/sys/mailaddressaliasservice

```

repro:
* create premium account
* add whitelabel domain
* go to global settings -> add custom domain with the same domain
* in step 3, click the checkmark button next to the email text field while the text field is empty
* get bad request error

# Test notes
see #4226

### PR DESCRIPTION
**Pull request by paw-hub**
Closes #4226 and closes #4244

Test notes are on #4226

### CODE REVIEW

**Review by ganthern — COMMENTED** [review]
I think `checkAndGetErrorMessage` is only used for user imports?

Signup and Alias creation use another method, like in `SelectMailAddressForm.ts`

**Comment by SnowyMouse** [comment]
> I think `checkAndGetErrorMessage` is only used for user imports?
> 
> 
> 
> Signup and Alias creation use another method for validation, like in `SelectMailAddressForm.ts`

Weird. From what I have found when working on this issue, my changes seem to work exactly as described for these exact features, which indicates this is used for more than just user imports.

Of course, I'll double check it again today. At least, I think this works? Of course, there is always a chance I did something wrong, and I did not commit the right change and I changed something else while rolling back the actual change. That's possible, too. And if so, if I found the real fix, I can probably re-find it!

**Comment by paw-hub** [comment]
So it seems I was actually not reproducing the issue, because the issue only occurs if *no* validation was done. If you go and type something in and then delete it, it will show the correct message.

Guess this will need fixed!

**Comment by paw-hub** [comment]
It's all fixed. Turns out this issue also affects adding groups and users via admin settings.

**Review by ganthern — APPROVED** [review]

**Pull request merged**
