### PR TITLE
remove expander's children when hidden

### PR DESCRIPTION
**Pull request by johnbotris**
otherwise they will be included in the tab sequence

We have to delay removal so that they can still do their shrink and fade out which is why it's tracked separately from attrs.expanded and done on a timeout

### CODE REVIEW

**Comment by charlag** [comment]
I don't know if it's better to remove or tabindex -1 but if you want to remove I would `then()` it after the animation

**Comment by johnbotris** [comment]
it's alot simpler to remove the whole node than to set the tabindex for all the children. Not sure what you mean by .then after the animation - it's a css transition

**Comment by charlag** [comment]
Ah yes, sorry, we changed that

**Comment by johnbotris** [comment]
it is a good point though - we could listen for transitionend instead

**Review by charlag — APPROVED** [review]

**Pull request merged**
