### PR TITLE
disable forward (shortcut and button) for external users

### LINKED ISSUE #2226: External recipients should not see Move (folders) button
It doesn't make sense since the user can't have custom folders, moving to Trash has its own button and moving to Drafts or Sent is not really useful.

image

### LINKED ISSUE #2227: Forward shortcut should be inhibited for external recipients
It doesn't do anything, but it also doesn't make sense.

**To Reproduce**
1. Login in to external user maibox
2. Click on email
3. Press Shift+F (forward)
4. See editor with empty (and read-only) To
5. Edit body and save draft
6. Get `BadRequestError`

**Expected behavior**
Pressing Shift+F should do nothing.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Pa7Hub**
fix #2226, fix #2227

### CODE REVIEW

**Comment by vitoreiji** [comment]
LGTM!

**Comment by Pa7Hub** [comment]
Awesome! :D

**Comment by charlag** [comment]
I think it changes the order of buttons in some cases (assign?), I'm not sure if we should do it

**Review by charlag — CHANGES_REQUESTED** [review]
Prevent changing the button order, like we dicussed
(just want to mark it as "request changes")

**Comment by charlag** [comment]
Buttons were actually not moved because of the mutually exclusive condition

**Pull request merged**
