### PR TITLE
make app resizeable

### LINKED ISSUE #1056: Unable to copy link url
When right clicking (or control clicking on Mac) a link, you get the option to copy, but it does not copy the URL, it only copies the text of the link. Some links I'd rather not open in the default browser, and the only way to do this is copy the URL and paste it in to the desired browser.

### LINKED ISSUE #2167: Tutanota Android app cannot be resized
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Resizing the tutanota app window is broken / not possible.

**To Reproduce**
1. Open tutanota app on an Android Desktop environment
2. Try to resize it

**Expected behavior**

Resizing is possible

**Screenshots**

As you can see, even the resizing button is greyed out. Dragging edges or corners is also not possible.

Screenshot_20200727-093444_Tutanota

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S6
 - OS: Android 10
 - Version: `v3.73.1`

**Additional context**

I'm using [Samsung DeX](https://www.samsung.com/us/explore/dex/), which gives a desktop like experience and makes use of Android windowing support.

[Samsung has documentation on how to enable window resizing](https://developer.samsung.com/samsung-dex/modify-optimizing.html):

```xml
<application
    android:resizeableActivity="true">
</application>
```

This documentation also has more tweaks and information on how to improve the desktop experience in case you're interested.
They also have [an app testing guide](https://developer.samsung.com/samsung-dex/testing.html) (although some apps are fine with this guide but won't work on "real" DeX sometimes).

Applications like Firefox, VLC or Termux can be resized without any problems.

**PS:** I know that it is possible to _force_ all apps to be resizable via `Samsung Labs` > `Force Resize` but it would obviously better to make the application natively resizable to create less friction.
**PPS:** I'm not sure whether this is relevant but [this](https://codeberg.org/gitnex/GitNex/pulls/601/files) is how GitNex fixed the issue and [this](https://github.com/TobiGr/NewPipe/commit/ea486e769ff9728c4e5d7dac6028587c39476fa9) is how NewPipe fixed it.

### PR DESCRIPTION
**Pull request by antifarben**
This PR makes the app resizeable on Android Desktops and should fix #2167

**PS:** If you're going to merge this: would you be so kind and add the [`hacktoberfest-accepted`](https://hacktoberfest.digitalocean.com/hacktoberfest-update) label to this PR? Thank you in advance!

### CODE REVIEW

**Comment by charlag** [comment]
Hi, how does this relate to #1056 ?

**Comment by antifarben** [comment]
Sorry, my fault. It should be #2167.

**Comment by charlag** [comment]
>If your app targets API level 24, but you do not specify a value for this attribute, the attribute's value defaults to true. 

https://developer.android.com/guide/topics/ui/multi-window#resizeableActivity

As we target API 29, we don't have to do anything:

https://github.com/tutao/tutanota/blob/36db43dd18640636d78a4ad006636d14fa179e69/app-android/app/build.gradle#L6-L9

**Comment by charlag** [comment]
I also could split screen it without any problems

**Comment by charlag** [comment]
If you want to open another PR which specifically targets Samsung DeX it would be nice but we can't really test it

**Comment by antifarben** [comment]
> If you want to open another PR which specifically targets Samsung DeX it would be nice but we can't really test it

[If I'm not wrong, the documentation doesn't mention another possibility](https://developer.samsung.com/samsung-dex/modify-optimizing.html#Enabling-Multi-Window-support).

**Comment by charlag** [comment]
Hm, maybe they ignore target version.
Did you check that it does help?

**Comment by antifarben** [comment]
I have two DeX capable devices and resizing worked on those with explicit `android:resizeableActivity="true"`.

**Comment by charlag** [comment]
Ok, then it seems like they really look in the manifest. I'll add a comment and merge it.

**Pull request merged**
