### PR TITLE
Chinese languages

### PR DESCRIPTION
**Pull request by guoyunhe**
Current Tutanota web client has some problems for all Chinese users, both Simplified and Tranditional.

For Traditional Chinese users: here are two Traditional Chinese files: `zh_hant.js` (63% translated) and `zh_tw.js` (100% translated). They are the same language. `zh_tw.js` should be used but it didn't. So I deleted `zh_hant.js` and you should also delete it from PhraseApp.

For Simplified Chinese users: `zh.js` is not loaded. I included it in languages and changed the language match rules: when given `zh_cn`, it first try to find `zh_cn`, then try `zh`, then try any other begin with `zh_*`. Now it can show proper translation in Simplified Chinese:

screenshot_2018-10-09 tutanota

### CODE REVIEW

**Comment by charlag** [comment]
Hi!
Thanks a lot, I will have a look this week!

**Comment by charlag** [comment]
Rather than making a lookup hack, can we just move one translation to another and delete another one?

As I understand, for browser zh_hant language we should show zh_tw (best trandition translation). Can we just delete current zh_hant and rename it into zh_tw?

For zh_cn we should show zh (best simplified translation). Can we rename zh into zh_cn and remove zh?

It may be that this lookup you added is really needed but I want to clarify that. Please correct me if I'm wrong.

**Comment by guoyunhe** [comment]
@charlag I think your solution can get the same result. I don't rename files because I don't know if PhraseApp supports renaming without losing existing translations. If PhraseApp does support renaming language code, it is okay to do so.

**Comment by charlag** [comment]
@guoyunhe okay, thanks a lot! Would be nice to hear some translators. We don't need to actually "rename", we probably can just delete and upload another one.

Actually after reading a little bit and checking examples
(see this line https://github.com/apple/swift-corelibs-foundation/blob/master/CoreFoundation/PlugIn.subproj/CFBundle_Locale.c#L193) I think that lookup may be okay.

Another example is MDN which has zh-CN and zh-TW.

zh_hant and zh_tw are techinically different.

> zh-Hant (Chinese written using the Traditional Chinese script)
while zh_tw is a regional code. We should discuss the way to straightforward this.

**Comment by guoyunhe** [comment]
If the language code is for detecting browser languages, use `zh_cn` and `zh_tw`. Both HTTP headers and JavaScript navigator.languages provice `zh-CN` and `zh-TW` by default. `zh-Hant` and `zh-Hans` are rarely used. You can simply symlink `zh_hans` to `zh_cn` and `zh_hant` to `zh_tw` for a full support.

Here is a long story for Simplified Chinese and Traditional Chinese. In mainland on China, Simplified Chinese is official writing language but Traditional Chinese is still used in some books. Taiwan had been using Simplified Chinese for a while but finally they turned to Traditional Chinese for several reasons. Traditional Chinese used in Hong Kong and Macau are different with Taiwan.

If you ask Chinese people to write in Traditional Chinese (zh-Hant), you will get three different writing because here are different Traditional Chinese. To serve people the best reading experience, providing languages by regions is better. Here are mainly four official Chinese language standards by regions:

1. zh-CN
2. zh-TW
3. zh-HK (the writing language of Hong Kong and Macau is the same, almost no difference in characters and vocabulary)
4. zh-SG (though not official language anymore, still widely used in south-east Asia)

With these four languages, you can serve almost all Chinese users.

**Comment by charlag** [comment]
Thanks a lot, I think we will start from fixing zh-CN & zh-TW and fall back to one of them for others zh variants

**Comment by guoyunhe** [comment]
Hi @charlag What is the current situation of this pull request? Have you made any changes of renaming translation files from PhraseApp? I am really interested in to help this feature because for Chinese users app is a mix of outdated Traditional Chinese and English (which is worse than only English).

**Comment by charlag** [comment]
Hey
We're a little bit overwhelmed right now because of thr new client release but we want to come to it soon, don't worry, I didn't forget!

**Comment by charlag** [comment]
#929 does almost the same thing as this PR, just with zh_hk special case

**Comment by guoyunhe** [comment]
PR #929 is better. So close this.

**Comment by charlag** [comment]
Thanks for your help!

**Pull request closed without merging**
