### PR TITLE
Rdv osm event

### PR DESCRIPTION
**Pull request by padawin**
This is a follow up PR for https://github.com/tutao/tutanota/pull/1569

### CODE REVIEW

**Comment by charlag** [comment]
hi, thanks for the PR!
I think it should be fine but maybe it could be even better if the button was hidden when the address is empty. You can just return `null` in `injectionsRIght` conditionally.

**Comment by charlag** [comment]
hi, thanks for the PR!
I think it should be fine but maybe it could be even better if the button was hidden when the address is empty. You can just return `null` in `injectionsRIght` conditionally.

**Comment by padawin** [comment]
Done :+1:

**Comment by charlag** [comment]
Cool, thanks a lot, will try to merge it soon!

**Comment by charlag** [comment]
Uh, I merged first and then rebased and Github didn't get that it's merged. Sorry.

**Comment by padawin** [comment]
No problem :-)
Thanks for merging it!

**Pull request closed without merging**
