### PR TITLE
Add Saturday to week start options - Fix #1941

### LINKED ISSUE #1941: First day of a week
Hi,
First day of a week in some countries in middle east is SATURDAY.
please add this to the Android App.

### PR DESCRIPTION
**Pull request by divarre**
- add the ability to display calendar with Saturday being the first day of the week
- rename firstDayOfWeekFromSundayOffset to firstDayOfWeekFromOffset for clarity as Saturday can be an offset
- add Saturday as an option in the Appearance Settings
- add comment to clarify how names of the days are generated

### CODE REVIEW

**Comment by vitoreiji** [comment]
Looks good to me!

@bedhub can this go in the next release?

Thank you @divarre :-)

**Comment by charlag** [comment]
`firstDayOfWeekFromSundayOffset` originally meant that in JS week starts on Sunday but I am okay with renaming

**Comment by charlag** [comment]
It's not merged into master, @vitoreiji you merged it into calendar-week-improvements

**Comment by charlag** [comment]
I merged it

**Pull request merged**
