### PR TITLE
Fix tabbing not working properly

### LINKED ISSUE #6661: Tab takes focus out of text editor
When writing a mail, pressing tab does not indent, but takes focus out of the text editor.

Expected behavior: pressing tab indents text.

## Test notes
- [ ] Create a bullet list with two items. Go to the second item and press tab, and verify that the entry is indented
- [ ] Verify shift-ctrl-z (redo) still works
- [ ] Press tab without a list and verify that an em space is inserted instead.

### PR DESCRIPTION
**Pull request by paw-hub**
Fix the workaround for fixing ctrl-shift-z so that tab is still recognized correctly for list indentation.

Fixes #6661

### CODE REVIEW

**Comment by murilopereirame** [comment]
Seems ok, but the original issue talk about tab for padding in general, is it ok to just pad bullet list items?

**Comment by paw-hub** [comment]
My original complaint on Wire was that we completely broke tabbing on bullet points in a very recent commit, and this fixes that.

As for indenting on lines without bullet points, I don't think we ever did this?

**Comment by murilopereirame** [comment]
> My original complaint on Wire was that we completely broke tabbing on bullet points in a very recent commit, and this fixes that. As for indenting on lines without bullet points, I don't think we ever did this?

I'm not sure if we ever handled the tabs. So I think it's ok, the bug is fixed

**Review by murilopereirame — APPROVED** [review]

**Comment by paw-hub** [comment]
I added a commit that also adds the em space when tab is pressed. I'm not entirely sure this is what we want, but it's here.

**Pull request merged**
