### PR TITLE
fix faq hyperlinks

### PR DESCRIPTION
**Pull request by prnam**
Fixed as mentioned in  #3311

### CODE REVIEW

**Comment by vitoreiji** [comment]
Now I'm thinking if this should not be part of #3743. @bedhub would be the best person to judge that atm, I think.

**Comment by prnam** [comment]
@bedhub, what do you think?🙂

**Comment by prnam** [comment]
@vitoreiji , what shall be done on this issue? I guess @bedhub  is AFK.

**Comment by charlag** [comment]
We still don't know when we will finish settings rework, sorry @prnam

**Comment by prnam** [comment]
I am thinking to close this PR. If no objection @vitoriji and @charlag, shall I proceed?

**Comment by vitoreiji** [comment]
Sure, sorry it is taking so long, we are focusing on other things at the moment, but we'll get around to it soon-ish.

**Pull request closed without merging**
