### PR TITLE
Update gradle-wrapper.properties

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds the `distributionSha256Sum` property to `gradle-wrapper.properties`. It allows for verification of the downloaded Gradle distribution via SHA-256 hash sum comparison.

You can find some documentation about this security improvement [here](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:verification), and the sums for each version of gradle [here](https://services.gradle.org/distributions/).

Note that you need to update this property every time you change your version of gradle.

#89

### CODE REVIEW

**Comment by charlag** [comment]
Hi!
Does it mean that we have to update it manually? Sounds like a pretty good idea to me

**Comment by Poussinou** [comment]
Yes you have to update it manually if you update your version of gradle.

**Comment by charlag** [comment]
Okay, makes sense! If you updated it for 4.4 I would gladly merge it (or I will do this later and close PR)

**Comment by Poussinou** [comment]
Done ;)

**Comment by charlag** [comment]
Thanks! :bowing_man:

**Pull request merged**
