### PR TITLE
Hide some faq entries for non-admin whitelabel users

### LINKED ISSUE #3150: Links to Tutanota faq are incompatible with whitelabel
As an customer who is using the whitelabel feature, i do not want my users to see any links to Tutanota domains. As an administrator of a whitelabel account it is fine to see those links.

We need to remove the links from these views for non-admins while in whitelabel mode (see also  #2057):
* login settings
    * https://tutanota.com/howto/#2fa (see also #2448)
* desktop settings
    * https://tutanota.com/howto/#tray-desktop
* mail authentication banner
    * https://tutanota.com/faq/#mail-auth
* image loading banner
    * https://tutanota.com/faq/#load-images

A more generic approach to take care of these links would be nice.

#### AC:
 *  [ ] A user in whitelabel mode does not see any links to Tutanota domains.

### Testing
see acceptance criteria (Check primarily in settings)

### PR DESCRIPTION
**Pull request by jowlo**
fix #3150

### CODE REVIEW

**Comment by vitoreiji** [comment]
As it is, this doesn't remove the links from the settings page. See #3305.

**Comment by charlag** [comment]
@jowlo is there something to do still to remove FAQ links?

**Comment by jowlo** [comment]
Well, actually i understood #3182 as an alternative to this one as it also takes care of the "links in the settings page" (although i dont know what it means). #3182 disables the FAQ completely for non-admin whitelabel accounts though.

I guess we need to decide on one of the two ways. I think the faq itself might still be useful, this PR just filters out some keys, ie `faq.2fa` and `faq.mail-auth, that don't really make sense in that scenario. However, all screenshots in other entries in the faq will reveal that its Tutanota, so maybe @armhub can clarify the original intent of #3150 and how strict we want this to be handled.

**Comment by jowlo** [comment]
This does not address the original issue in #3150 (links displayed in user settings). Also the we probably need to take care of the whole FAQ anyways in a whitelabel setting.

**Pull request closed without merging**
