### PR TITLE
Add dir="auto" to every paragraph in Editor

### LINKED ISSUE #2157: RTL support in mail editor
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web and smartphone apps**

**Describe the bug**
When writing in RTL languages, punctuation placed at the end of a sentence shows up at the beginning of it.
Inserting words from LTR languages such as English, changes the order of words in a sentence.

**To Reproduce**
1. Write a new email.
2. Write in an RTL languages and place a period at the end of it.
3. Period shows up at the beginning of the sentence.

**Expected behavior**
Punctuation and words from LTR languages should be placed where they are intended in RTL languages and not change the order of words in a sentence.

**Screenshots**

Screenshot from 2020-07-18 16:58:00

### PR DESCRIPTION
**Pull request by HassanHeydariNasab**
Fixes #2157 
Prior PR: #2333

### CODE REVIEW

**Comment by charlag** [comment]
Hey
I think blockAttributes will disallow it when reading it.
You should check Editor and squire for what you want to achieve.

**Comment by HassanHeydariNasab** [comment]
> Hey
> I think blockAttributes will disallow it when reading it.
> You should check Editor and squire for what you want to achieve.

Hi, what do you mean by "when reading it"?
Thanks

**Comment by charlag** [comment]
When we load content into the editor it is checked by the sanitizer. Your change tells sanitizer to remove dir attribute from HTML.

**Comment by HassanHeydariNasab** [comment]
> When we load content into the editor it is checked by the sanitizer. Your change tells sanitizer to remove dir attribute from HTML.

I think that you've been misinterpreted `block`. It means HTML tag.
The default block is `div`. For example here is a snippet from [here](https://github.com/neilj/Squire#setting-the-default-block-style) 
```
var editor = new Squire( document, {
    blockTag: 'P',
    blockAttributes: { style: 'font-size: 16px;' }
})
```
Here is the result I got:

**Comment by charlag** [comment]
Oh, it's really my bad, why did I think its sanitizer config?
You did exactly the right thing! My apologies.

**Comment by HassanHeydariNasab** [comment]
@charlag 
Any update?

**Comment by charlag** [comment]
@HassanHeydariNasab this should be okay to include in one of the next releases I hope @jowlo

**Review by mpfau — APPROVED** [review]

**Pull request merged**
