### PR TITLE
Optimize PNG image resource using zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
43 PNG images compressed losslessly as below, this will help distribute
applications with smaller size.

```
 app-android/app/src/main/res/drawable-hdpi/ic_status.png                   | Bin 612 -> 369 bytes
 app-android/app/src/main/res/drawable-xhdpi/ic_status.png                  | Bin 771 -> 447 bytes
 app-android/app/src/main/res/drawable-xxhdpi/ic_logo.png                   | Bin 14195 -> 10003 bytes
 app-android/app/src/main/res/drawable-xxhdpi/ic_status.png                 | Bin 1117 -> 653 bytes
 app-android/app/src/main/res/drawable-xxxhdpi/ic_status.png                | Bin 1453 -> 852 bytes
 app-android/app/src/main/res/mipmap-hdpi/ic_launcher.png                   | Bin 2465 -> 1853 bytes
 app-android/app/src/main/res/mipmap-mdpi/ic_launcher.png                   | Bin 1693 -> 1174 bytes
 app-android/app/src/main/res/mipmap-xhdpi/ic_launcher.png                  | Bin 3232 -> 2431 bytes
 app-android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png                 | Bin 4836 -> 3643 bytes
 app-android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png                | Bin 6320 -> 4850 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-1024.png          | Bin 26154 -> 9469 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-20.png            | Bin 580 -> 385 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-20@2x.png         | Bin 1048 -> 703 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-20@3x.png         | Bin 1535 -> 1011 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-40.png            | Bin 1048 -> 703 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-40@2x.png         | Bin 1999 -> 1269 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-40@3x.png         | Bin 2950 -> 1758 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-50.png            | Bin 1299 -> 885 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-50@2x.png         | Bin 2502 -> 1575 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-60@2x.png         | Bin 2950 -> 1758 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-60@3x.png         | Bin 4387 -> 2874 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-72.png            | Bin 1803 -> 1189 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-72@2x.png         | Bin 3574 -> 2004 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-76.png            | Bin 1897 -> 1254 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-76@2x.png         | Bin 3784 -> 2103 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-83.5@2x.png       | Bin 4091 -> 2231 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-small.png         | Bin 776 -> 508 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-small@2x.png      | Bin 1463 -> 979 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon-small@3x.png      | Bin 2177 -> 1410 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon.png               | Bin 1472 -> 966 bytes
 app-ios/tutanota/Assets.xcassets/AppIcon.appiconset/icon@2x.png            | Bin 2803 -> 1626 bytes
 app-ios/tutanota/Assets.xcassets/LaunchScreenIcon.imageset/icon-180.png    | Bin 4387 -> 2874 bytes
 app-ios/tutanota/Assets.xcassets/LaunchScreenIcon.imageset/icon-180@2x.png | Bin 9159 -> 6223 bytes
 app-ios/tutanota/Assets.xcassets/LaunchScreenIcon.imageset/icon-180@3x.png | Bin 14195 -> 10003 bytes
 resources/desktop-icons/icon/512.png                                       | Bin 13852 -> 11942 bytes
 resources/desktop-icons/icon/64.png                                        | Bin 1640 -> 1344 bytes
 resources/desktop-icons/logo-solo-red-small.png                            | Bin 1640 -> 1344 bytes
 resources/desktop-icons/logo-solo-red.png                                  | Bin 13852 -> 11942 bytes
 resources/encoded/hab.png                                                  | Bin 8601 -> 5872 bytes
 resources/encoded/notification-icon.png                                    | Bin 2905 -> 1687 bytes
 resources/encoded/paypal_logo.png                                          | Bin 2778 -> 1377 bytes
 resources/favicon/logo-favicon-152.png                                     | Bin 3136 -> 1944 bytes
 resources/favicon/logo-favicon-192.png                                     | Bin 3928 -> 2239 bytes
```

### CODE REVIEW

**Comment by charlag** [comment]
Hi
thanks for the PR!
I think it's a good idea for web resources (and maybe even for iOS, I need to check) but Android already does this automatically.
Another thing: we generate launcher logo pngs from svgs so it would be nice to automate this.

**Comment by PeterDaveHello** [comment]
Not sure if the Android automatically compressed result would be better or not(I'm not an Android developer), this optimization takes time, the automation task should be aware of images change before running the optimization work.

If those resources here aren't changed frequently, maybe can use the result for this time and work on the automation later?

**Comment by charlag** [comment]
Maybe you could give some references how to do this so that we can automate it?
I'm pretty sure Android does png-crunching as well as it's possible automatically.
I think that including it is still quite nice, just want to not break it later.

**Comment by PeterDaveHello** [comment]
Sure,

It's done by https://github.com/google/zopfli, and the parameter is ` --iterations=600 --keepchunks=iCCP --lossy_transparent --splitting=3 -my`, which should be lossless and strong optimization

**Comment by charlag** [comment]
Thanks for the hint, we'll probably add it to the build pipeline so that it's done automatically.

**Comment by PeterDaveHello** [comment]
As zopfli will take a lot of time, I'll suggest consider to get this one time compression merged, and integrate some not so extreme compression in the build pipeline to make sure it won't take too long.

**Pull request closed without merging**
