### PR TITLE
Remove cyclical references when writing logs

### LINKED ISSUE #2184: Logger chokes on cyclic objects
**Describe the bug**

The logger throws an unexpected error in getEntries if there are cyclic objects in the log, making it impossible to get the logs.

**To Reproduce**

1. Open Console and execute:
 `window.tutao.tutao = window.tutao`
 `console.log(window.tutao)`
2. click settings -> about -> send logs

**Expected behavior**
replace cyclic references in the JSON.stringify calls

**Desktop (please complete the following information):**
affects at least the desktop client (main and renderer thread, runtime and on app quit) and the web app

### PR DESCRIPTION
**Pull request by jowlo**
fix #2184

### CODE REVIEW

**Comment by jowlo** [comment]
Test notes:
 * Our own logger is disabled in local dev environment, force enabling, eg by
```
diff --git a/src/api/common/Logger.js b/src/api/common/Logger.js
index 484ce3dbe..ad479705b 100644
--- a/src/api/common/Logger.js
+++ b/src/api/common/Logger.js
@@ -71,7 +71,7 @@ export function createLogFile(timestamp: number, entries: Array<string>, scope:
 	}
 }
 
-export function replaceNativeLogger(global: any, loggerInstance: Logger, force: boolean = false) {
+export function replaceNativeLogger(global: any, loggerInstance: Logger, force: boolean = true) {
 	// Replace native logger only when enabled because we lose line numbers
 	if (force || global.env.dist || global.debug) {
 		global.logger = loggerInstance

```

**Comment by charlag** [comment]
I think we shouldn't print cycling objects and should try to avoid printing objects in general. I think decycling is too much overhead for each log statement.

**Comment by jowlo** [comment]
I think in general you are right, we should not log objects and definitely should not recurse on every log statement.

As far as i can tell, `formatLogEntry` is only ever called from `getEntries` which only gets called when someone wants to send Logs to us via the `About` -> `Send logs` method. I think that is the case when they want to report an error and we should not produce another error then..

**Comment by charlag** [comment]
If would simply wrap it into try/catch and replace it with `[cyclic object]` or something ilke that in case it happens. It's not pretty but it will work.

**Comment by jowlo** [comment]
Closed for lighter version with  #2575

**Pull request closed without merging**
