### PR TITLE
Make saving/discarding draft changes more explicit

### PR DESCRIPTION
**Pull request by jowlo**
Either closes the MailEditor when no changes have been made or opens up
a dropdown which lets you save, save and exit or discard and exit.

This has been asked for a few times on reddit:
 * https://www.reddit.com/r/tutanota/comments/d2qst4/wishlist/
 * https://www.reddit.com/r/tutanota/comments/kgtpje/i_miss_the_save_button_in_the_compose_message_form/

### CODE REVIEW

**Comment by charlag** [comment]
Is it intended that it's an icon?

I would do "save..." with ellipsys so that it's clear that there will be a dropdown

Screenshot from 2021-01-04 15-56-45
Screenshot from 2021-01-04 15-55-24

**Comment by jowlo** [comment]
The icon changes after having made changes. The layout was wobbling around a bit when it was saying "Save" instead of the hamburger icon. And the Dropdown has the option to discard, which is not really saving.

We could change it to the text version though.

**Comment by charlag** [comment]
I'm fine with icon but then I think we should use circle-less one like in the side menu but I would discuss with others, maybe someone insists on having text

**Comment by jowlo** [comment]
Another try after some discussions, no icons but text. The Dialog is modeled after the one by libreoffice

https://user-images.githubusercontent.com/6842104/103676781-c9cd9100-4f81-11eb-9d5c-f26f784a8877.mp4

**Comment by charlag** [comment]
I think save button is nice on the right but we need to check mobile/other languages too.
I am not sure about the dialog though. I think dropdown which you can dismiss is eaasier than to understand the message and press "cancel", I would leave it as dropdown with "discard changes" and "save and close" or something like that.
Another advantage of dropdown is that it's closer to the close button and not in the other part of the screen.

**Comment by charlag** [comment]
I think we agreed that we should make another proposal, probably with UI team

**Pull request closed without merging**
