### PR TITLE
Fix #1455, respect week start preference in calendar date picker.

### LINKED ISSUE #1455: Calendar date picker doesn't respect Week Start preference
**Bug in web app, mobile app, and desktop app**

**Describe the bug**
I have set the Week Start preference under Appearance -> User Settings to Sunday which is the typical week start day in North America.  The calendar reflects this, however when scheduling an event the date picker does not - the week still starts on Monday in the date picker.

**To Reproduce**
1. Set Week Start preference to Sunday
2. Go to calendar and see that Sunday is now the week start day
3. Add an event
4. Click the little calendar button in either the From or To section of the new event window to change the date
5. Notice that the week start is Monday in the picker, even though the preference for Week Start is set to Sunday

**Expected behavior**
The week should start on Sunday in the date picker when the user preference is set for the week to start on Sunday.

**Screenshots**
brave_2019-08-30_11-48-29
brave_2019-08-30_11-48-58
brave_2019-08-30_11-49-30

**Additional context**
This is an issue on the Desktop app, Android app, and web app.  I don't have an iphone but I assume it's an issue there too.

### PR DESCRIPTION
**Pull request by rdvincent**
A much more elaborate fix that avoids polluting the date picker with specifics of the model.

Requires changes to modules (White label/Contact form) that I cannot properly test in my configuration.

### CODE REVIEW

**Comment by charlag** [comment]
@rdvincent hi, sorry for the delay, I looked it over the weekend and it looked nice but I didn't have time to merge it yet, will try to do it this week!

**Comment by rdvincent** [comment]
No worries. Feel free to suggest any other bugs or features I could work on.

**Comment by charlag** [comment]
After we merged it I noticed some issues highlighted by the type checker. Please pay attention to flow checks. We already fixed them.

**Comment by rdvincent** [comment]
Sorry, I was using dist build, naively following the BUILDING.md instructions, and so not seeing the flow warnings.

**Comment by charlag** [comment]
No problem!
Also if you will want to make some other changes there's a much faster `make` script, see [HACKING](https://github.com/tutao/tutanota/blob/master/doc/HACKING.md).

**Pull request merged**
