### PR TITLE
add "Delete all" to Sent folder

### PR DESCRIPTION
**Pull request by chovy**
add "Delete all" to Sent folder

Its very time consuming to delete each email individually from the Sent folder.

As a privacy conscience app I'd like to clear out the Trash and Sent folders easily.

### CODE REVIEW

**Comment by armhub** [comment]
Sorry, but we already have the possibility to delete all contents from a folder by selecting "Edit" -> "Delete" on that folder. We chose to have the "Delete all" button only on the trash and spam folder because these are the ones that you are likely to delete more often.
But thanks for your effort anyway!
Arne

**Comment by chovy** [comment]
I delete from Sent all the time.

**Comment by kwolk** [comment]
There used to be a time when the service provider would automatically delete sent emails, when space was at a premium… think Hotmail.  Then GMail came along with 1GB for free, it was about the only time Microsoft was ever secure :-)

**Comment by chovy** [comment]
I'm more concerned about privacy. no reason to leave emails hanging around in ./Sent or ./Trash.

**Pull request closed without merging**
